language: java
jdk:
- oraclejdk8
services:
- postgresql
before_install:
- psql -c "create user flowchat with password 'asdf' superuser" -U postgres
- psql -c 'create database flowchat;' -U postgres
- cd ui; yarn; yarn build --prod --aot;
- cp -R dist/ ../service/src/main/resources
- cd ../service
- echo -e 'jdbc.url=jdbc\:postgresql\://127.0.0.1/flowchat\njdbc.username=flowchat\njdbc.password=asdf\nsorting_created_weight=86400\nsorting_number_of_votes_weight=0.001\nsorting_avg_rank_weight=0.01\nreddit_client_id=\nreddit_client_secret=\nreddit_username=\nreddit_password='>flowchat.properties
addons:
  postgresql: '9.3'
  apt:
    packages:
    - sshpass
env:
  global:
  - secure: kRNtgp2nlEozBOkRa1GaaVaOFwu11lfWIL+LvJKnUhFR9cfHy03W6pfIBYgFrlhU4fkNM0iFtQs1WlvHuBa8DuHYr4xDyLJLDfdDEry+/0yd88UQsIzV2KIwa/aKUR77Ruq0P5d/h2ArB6Oxd21qf39+SN/ZSe0aCxZZvOK68NIDw2fdODhdF/36vxt1N7n7HqSKlpU7cPDhWn6lN0rdrbhuUO6QTVvvYGEjkSJAjRNOBTerKz0ioFzqoYpErSPwufAYEdrPsRJD2iKhlfxIN1SmL5EnY701WlSoMFpEvz7XvSwGwvk9CGlDleV8IZssSsrXVBxsNLQ5GU60SkD4B/QROg3BqeFKTx0JZEYcObiSamHPdogMMsPIeTfyfe9R72Ws5uDEGTh0e0l3GRzebxPfA3mo25bU+MLEC+pHakb5e5Ck7JnEXJD9Ci9e0VG70U6c0E/55YdhPzo6m2GN3cex4+305oPcFB2d+GcywC0bBle4uWVOyKePoVgrsMOVyWFAbPGbIQNv+nVIJpaHj7b1mN6mnvRXcTlHV3zGT5nNbbjLIurCsaLLDX0XkoKpPZz3vkmzARpSMOAKS8+bw3B47KPcVk/SVKR1thvtp4BRwwxTyDrUHfNpLUx6K9QcjZFRBmIzkg2oK/xcdGqYWasBEt6VjZ4n6qTFpWjCxoc=
  - secure: v/QhYQtjlqB0y52ZsLhoAyt2ecmQ6CCnxdjH+jM2pTG9QCsTTxLoZo+4AxImqsyVieQVdPZ2TJwwlQzikDUORfa/HQJ6EKNJWF1p68kPAGgpxuuAwX+lle7us31DzNfbWDnLlzBNdtJC5F3W1cFhQQqDj5C/T/XGMKHp/GJrFW7kVtmM2KYwjqoMqf2kmUAu8yuOAUzJCxTrGfQGj5vr9FblBOkCNzoNMNh/PNFA3QP9TzpuB2NBcJRayjcUz66IQd46c81e/ftHkP7ITOjJaEi+21zqhsfX2s6uYwNUpJtpkShF5ijyoHXENV9lomEzo0F13xOfYpnJdc7wQI9NjBQk9UACDj63AvhW+J7PfdDcja/lSmtfItid5/7Y2UlzoKhyO84VzVmiLoqHZJfBbbBKlk37wONTw4YTvLo+9SLpDUSnlKqwZq2Qs5PRnthiOj/2V3Ox2AUF4ZIgiHI7EOOyGiEELJm+Lv63a4yEVFwNyE8cIsky17OOEpKnbMeer91KJzem9mU3qODERr5+3MGdWdf1Jzmyz1DJVzCiaVv/tyAOgjuUremIGToOeg+2z2Ttocq0QqlCqA5MoaFARXXsRN2mtm/wVCZU56z4mA1H2DOJNLX9Jf8b80wkIc+y74e41hVwM2Y8dM9D32/V5yyOOK22J+Geg7h4STCkNyo=
  - secure: U6Gck9mBRuJv+rJ0zIltpFJ4PTNUNw2uHkkqf5wn226Lned7DiShNapNzCJg14u9r8JOAaCWGL8rADUP9qHl4iDGFSX+JAdgDuPFKrgE8QfRKlIwA9wICUgXr9n9SQ/EE63iDKs5EmPpypUZfRztaa+kcpUkcowC2NJppLMSJTLNLx/+PVytkLHG6SV+ztHEzTBpdSrw1qKBotlLwsliHBQ3RIe/z6CsCpDiRRfw7jehviYQOBt2CuXNBdGr+vNoqYTM1aaNF8mzacONTmjJ163xcI1VQB7yXaI3kfYVTb79EG01cuBT6Dno72kN34IFIOBMy9KXk9aS/Es2m47vzyqHoL5h0z7+GnvNPlMuyoyJ6OM+gpYVSFdsUsT0P2vAupmpbsWEd1h1V7nJjjBj8QPBkVPaCfogUjxNQELvkItYTrc3qC5pyQTl3dVNpr+b/jAcRWz1JSwbwWZWcW/axsFd1S6OvTf88sx2UAK5bYkVV1hT4AiP3Tf2XJfwQG8kWH23sNka/+hxAAl7ALz27tYOETfiMrAVoDSeck6h7yzzVKcbYQ1GPsmIrypWT+s6vTj+S+2fzQr1wMRlGhUjvIQdfz8kyvQOYfrlKiaI0Nc7z/Ds4saCmjVF5SlkXshroJHM/n2ojia46bYS1h6JJsMXutUwSuOLHrIA0TZRD7o=
deploy:
  provider: releases
  api_key:
    secure: JorCWY30UiSI5DWIlDbhKX0zHp+vB4u0+8354jYYHGGmKUoY4DjbLtaJ8wwt52QmhEhPMNQxU1siS41kwGqgm0uLX6zH9BJTB5Nh/1EEkSuoKpY8GgnCsXX+gV+ic+yTFDpqavyP7Xru8I7OfQt62fbBNApDpOEPPLzLYdWb+ILbo1OoGKgEN2s4UyuVllEniqxAMcTZg5IwqCDuGW2bZxopYu9WdkQvpGYmvI3HR47AHpV40OEB1i5JmRBBNOuJTdeRoD9bw0DecL0hv5eY4IHA4evttUdZQ0m33bGM89/d5CKUpgOloJprVQTFfF0iazGX0maJG2PeJzHDxfYtDtEccFhY26EVPUJZAfw6Zx+LS2surHH3rxc+wF2wiRQ1YEu0PUuBK/3OoIFVEeCPGoLAgWfOYTSnhtlxozwOgdzLwwqjwp1yxJx+cVx67wBwNoz3zcEdObmzI/1FrU1A9UwZmi8ciI4cTheEbhQkzN+yiZFsSD0wfm+pahKABkuuVJbdKUUiFgNHvBYWmFcflnexrUQ4rBLDPFvanRHe0bRtI21Z/T0uT6yBf89Y3ksV5Lb+oxUCzQvbefhIpdr/yTRm8ihhTUDcpBkSd6ztelTR1GBQaLjDLKFqbeLZIItrlsz4sE60gUGMQHDdP7fPuWD4aK95EsdvjoKjLDRzB6E=
  file:
    - target/flowchat.jar
  skip_cleanup: true
  on:
    repo: dessalines/flowchat
    tags: true
before_deploy:
- echo $PWD
after_deploy:
- cd ..
- ./deploy.sh
